apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: get-kubeconfig
  namespace: ops-system
spec:
  desc: copy kubeconfig from etc to ~/.kube/config
  steps:
    - name: get-remote-kubeconfig
      remotefile: /etc/kubernetes/admin.conf
      localfile: ~/.kube/config
      direction: download
