apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: list-pods-resources
  namespace: ops-system
spec:
  desc: list pod resources requests in cluster
  host: anymaster
  variables:
    namespace:
      required: true
  steps:
    - name: list-pods-resources
      when: ${namespace} != "all"
      content: kubectl get pod -o custom-columns='POD-NAME:.metadata.name,NAMESPACE:.metadata.namespace,RESOURCES-REQUESTS:.spec.containers[*].resources.requests' -n ${namespace}
    - name: list-all-pods-resources
      when: ${namespace} == "all"
      content: kubectl get pod -o custom-columns='POD-NAME:.metadata.name,NAMESPACE:.metadata.namespace,RESOURCES-REQUESTS:.spec.containers[*].resources.requests' -A
