apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: restart-containerd
  namespace: ops-system
spec:
  desc: restart containerd
  steps:
    - name: restart-containerd
      content: |
        systemctl restart containerd
    - name: check-containerd-status
      content: |
        systemctl is-active containerd
    - name: check-containerd-active-enter-timestamp
      content: |
        systemctl show containerd -p ActiveEnterTimestamp