apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: velero-uninstall
  namespace: ops-system
spec:
  desc: uninstall Velero
  host: anymaster
  steps:
    - name: uninstall-velero-server
      content: kubectl delete namespace/velero clusterrolebinding/velero & kubectl delete crds -l component=velero
    - name: clear-env
      content: rm -rf velero*
