apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: velero-status
  namespace: ops-system
spec:
  desc: status Velero
  host: anymaster
  variables:
    velero_version: 
      default: v1.9.2
  steps:
    - name: backup-status
      content: ./velero-${velero_version}-linux-amd64/velero get backups
    - name: restore-status
      content: ./velero-${velero_version}-linux-amd64/velero get restores
